-- Role: usersadmin
-- Password: useradmin

CREATE ROLE usersadmin WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:qCgi/ZcwsF0XbzwaNSLUpw==$vSwWU0HZtFwFOKGouRkE9HiNzAWRpJN7W+vVH303y80=:a9icbWZQcFE/ZaEgH7V7uPz4HnN72fCPJ02bpDohmok=';
